travis:
  secure:
    BINSTAR_TOKEN: Lk8Xi//SxXzs5VqybNYMnFKbKANB60dC48bmZhCF8zbdTOpPUev3yKK9SqEX+LIDpS1v0RHKBOFysYkROf5OLeMmcvACERZxLyFRR+h6jH7lFB4TRimcydl4BJ8M11hlqsgXQYKBsM6uUrVWdGS28hclIHMJTItIgPIY6I4wsPdbAlL1lptbagq/VxsgTg6KD7XqFh+eoslxE5cjB+xwtQJH8QNSdhenwLWKL5W70vKU+DME/8dLpVbp5MYsE4TmiHE6s1D88kHqa+V4I4upu7+6gC635NcuNZx+KgI6309bme4BHAdM6mIsRl6oL/kWqIyreOU4B3BtzywPnnDhTvOknaHJ5qsrgO3ka3p7JEh2S9lEACyEsPBBO1xuEO6Mf36fwsRFV9kEFSl8YsByPUkhwvghcgjbgNnTq262YQp2dIY1DNw+vEDBFhErSqmGwMGghyUz9Hi0nfRZLrlq3RISM1Lsg/KEIkDCW+nlAybB9PVnZ40REhmAROl9gKiTKJIA7sD3DHNsk0wf+lnXCScbu4y8EnpbH5ZBNO9PAh12LoM+dlHnFRLZTJ45Zdu5SATiryQjoEXczO6YNzLipw8JZGsXL8nZXysWyebhQ12YXz+geH4du8TtDkoM/RXtsgBc4TgmJvgOI7StUjXio3bKuKjM7Jn+rAugn0shSqc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
